feature-exercicio-nivelamento-02
PabloDamato/Orion-Bootcamp-Nivelamento-TypScript pull request #5
Opened 2024-10-03 00:22 UTC by PabloDamato

2024-10-03 21:05 UTC, samuelcamilocosta requested changes

2024-10-03 21:05 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +  lista: { id: number; name: string; bio: string }[]
tu criaste a interface do tipo Lista, faltou implementar ela nas demais funções que está utilizando a lista dessa forma, para ficar organizado :)

2024-10-03 21:05 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +      console.log(lista);
esse é apenas um bizu:
como o console.log(lista) é do tipo void, você pode colocar return console.log(lista);

2024-10-03 21:05 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +  } else {
como a função utiliza return para parar ela quando cair no if, você pode remover o else e deixar apenas o return console.log

vou deixar um artigo que explica um pouco sobre os benefícios que possa vir de se omitir um else em momentos que ele não é necessário
https://pauloreal.medium.com/saiba-o-porque-voce-deveria-evitar-o-else-no-seu-codigo-792c8abc5683

2024-10-03 21:05 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +//Samuel, segundo a minha pesquisa, na documentação diz que o método find() retorna undefined caso o valor informado não satisfaça a condição, que, nesse caso seria lista.id igual ao id passado via p
perfeito, pode remover esse comentário do código, você consegue responder meus comentários adicionados no code review e discutirmos sobre eles, também pode remover os comentários de correções feitas, fica todo um histórico salvo que podemos ver nos reviews de PR do que foi alterado, não se preocupe

2024-10-03 21:05 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +      console.log(lista);
aqui também cabe aplicar o return console.log(lista);

2024-10-03 21:05 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +  lista: { id: number; name: string; bio: string }[]
seria bom aplicar a interface criada para a lista aqui e nas outras funções, já que estamos tratando sempre da mesma lista

2024-10-05 00:47 UTC, samuelcamilocosta requested changes

2024-10-05 00:47 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +interface lista {
no Typescript quando vamos criar uma interface, por convenção nós iniciamos o nome delas com -> I, ajuda a identificar que é uma interface, para esse caso "ILista", porém a interface criada se refere a um item da lista, então faria mais sentido "IPessoa". É bom a gente se atentar bastante aos nomes que damos as variáveis/interfaces, pois eles fazem o nosso código ficar mais legível e fácil de entender.

2024-10-05 00:47 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
> +  const index:
O find não retornará um index e sim um item da lista. Assim o nome index para a variável deixa o código confuso.

Criou a interface, porém faltou aplicá-la aqui `IPessoa | undefined`

2024-10-05 00:47 UTC, samuelcamilocosta commented on src/exercicio_nivelamento_2.ts
Seria bacana documentar as funções com o TSDoc.

https://tsdoc.org/

2024-10-05 10:36 UTC, PabloDamato commented on src/exercicio_nivelamento_2.ts
> +interface lista {
Opa, legal Samuel, obrigado pela dica: realmente eu fiquei confuso na hora de criar e devido o nome do arry que foi apresentado ter vindo com o nome lista eu fiquei meio que na dúvida se eu poderia mudar o nome, mas nesse caso faz mais sentido Pessoa mesmo. Vou atualizar o código.

2024-10-05 10:41 UTC, PabloDamato commented on src/exercicio_nivelamento_2.ts
> +  const index:
Samuel, eu alterei para Id, faz mais sentido, né? já que a principal função está na busca pelo ID de alguma pessoa presente na lista por este código: 

lista.find((person) => person.id === id.

Sobre a interface, eu havia conseguido aplicar ela no código dessa maneira:

const Id:
    | {
        id: number;
        name: string;
        bio: string;
      }
    | undefined = "busca o id da pessoa..."

Eu não sabia que eu podia aplicar direto assim:

const Id: IPessoa | Undefined = "busca o id da pessoa..."

Vou atualizar o código. 
Atualizei também as outras funções em que eu havia realizado a mesma prática, valeu pela dica.

2024-10-05 10:41 UTC, PabloDamato commented on src/exercicio_nivelamento_2.ts
Vou documentar as funções com o TSDoc.

2024-10-05 12:32 UTC, samuelcamilocosta approved these changes

2024-10-05 12:32 UTC, merged